/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { TestResultCommonSchema } from '../common';
import { TestData as PartialCatAM2TestData } from './partial';
import { SafetyAndBalanceQuestions as PartialCatAM2SafetyAndBalanceQuestions } from './partial';
import { TestData as CommonTestData } from '../common/index';
import { VehicleDetails as PartialCatAM2VehicleDetails } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';

export declare namespace CatBUniqueTypes {

  type TestData = PartialCatAM2TestData;
  type SafetyAndBalanceQuestions = PartialCatAM2SafetyAndBalanceQuestions;
  type VehicleDetails = PartialCatAM2VehicleDetails;

}
