/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { TestResultCatAM2Schema } from './partial';
import { TestData as CatAM2TestData } from './partial';
import { SafetyAndBalanceQuestions as CatAM2SafetyAndBalanceQuestions } from './partial';
import { VehicleDetails as CatAM2VehicleDetails } from './partial';
import { CategoryCode as CatAM2CategoryCode } from './partial';
import { Circuit as CatAM2Circuit} from './partial';

export declare namespace CatAM2UniqueTypes {

  type TestResult =  TestResultCatAM2Schema;

  type TestData = CatAM2TestData;

  type SafetyAndBalanceQuestions = CatAM2SafetyAndBalanceQuestions;

  type VehicleDetails = CatAM2VehicleDetails;

  type CategoryCode = CatAM2CategoryCode;

  type Circuit = CatAM2Circuit;

}
