/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { PartialTestResultCatCESchema } from './partial';
import { TestResultCommonSchema } from '../common/index';
import { PassCompletion as CommonPassCompletion } from '../common/index';
import { TestData as PartialCatCETestData } from './partial';
import { TestData as CommonTestData } from '../common';
import { TestRequirements as PartialCatCETestRequirements } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';
import { Manoeuvres as PartialCatCEManoeuvres } from './partial';
import { VehicleChecks as PartialCatCEVehicleChecks } from './partial';
import { JournalData as PartialCatCEJournalData } from './partial';
import { JournalData as CommonJournalData } from '../common/index';
import { Candidate as PartialCatCECandidate } from './partial';
import { Candidate as CommonCandidate } from '../common/index';
import { VehicleDetails as PartialCatCEVehicleDetails } from './partial';
import { VehicleDetails as CommonVehicleDetails } from '../common/index';

export declare namespace CatCEUniqueTypes {
  type TestResult = PartialTestResultCatCESchema & TestResultCommonSchema;

  type TestData = PartialCatCETestData & CommonTestData;

  type TestRequirements = PartialCatCETestRequirements & CommonTestRequirements;

  type Manoeuvres = PartialCatCEManoeuvres;

  type VehicleChecks = PartialCatCEVehicleChecks;

  type JournalData = PartialCatCEJournalData & CommonJournalData;

  type Candidate = PartialCatCECandidate & CommonCandidate;

  type VehicleDetails = PartialCatCEVehicleDetails & CommonVehicleDetails;
}
