/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema definition for application configuration
 */
export interface AppConfig {
  googleAnalyticsId: string;
  approvedDeviceIdentifiers: string[];
  timeTravelDate?: string;
  role: "LDTM" | "DE";
  journal: {
    journalUrl: string;
    searchBookingUrl: string;
    autoRefreshInterval: number;
    numberOfDaysToView: number;
    allowTests: boolean;
    allowedTestCategories: string[];
    testPermissionPeriods: {
      category: string;
      from: string;
      to?: string;
    }[];
    enableTestReportPracticeMode: boolean;
    enableEndToEndPracticeMode: boolean;
    enableLogoutButton: boolean;
  };
  tests: {
    testSubmissionUrl: string;
    autoSendInterval: number;
  };
  logs: {
    url: string;
    autoSendInterval: number;
  };
  user: {
    findUserUrl: string;
  };
  requestTimeout: number;
  [k: string]: any;
}
