/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema definition for MDM configuration
 */
export interface MdmConfig {
  /**
   * Flag to define if the app should use the remote config instead
   */
  isRemote?: boolean;
  /**
   * Remote config url
   */
  configUrl: string;
  /**
   * A number of days that the logs are cached
   */
  daysToCacheLogs: number;
  /**
   * Flag to enable dev tools
   */
  enableDevTools?: boolean;
  /**
   * Flag to enable store rehydration plugin in browser
   */
  enableRehydrationPlugin?: boolean;
  /**
   * Flag whether the logout clears test presistence or no
   */
  logoutClearsTestPersistence?: boolean;
  /**
   * Api key for logs post
   */
  logsPostApiKey: string;
  /**
   * Url for the logs api
   */
  logsApiUrl: string;
  /**
   * Time in milliseconds which sets the interval that the logs are sent up
   */
  logsAutoSendInterval: number;
  authentication: Authentication;
  sentry?: Sentry;
}
/**
 * Authentication related configuration properties
 */
export interface Authentication {
  /**
   * Authentication context
   */
  context: string;
  /**
   * Resource Url
   */
  resourceUrl: string;
  /**
   * Client Id
   */
  clientId: string;
  /**
   * Redirect Url
   */
  redirectUrl: string;
  /**
   * Logout Url
   */
  logoutUrl: string;
  /**
   * Key for the employee Id
   */
  employeeIdKey: string;
}
/**
 * Sentry error logging service configuration properties
 */
export interface Sentry {
  /**
   * Sentry application specific data source name (DSN)
   */
  dsn: string;
  /**
   * dev / uat / prod
   */
  environment: "dev" | "uat" | "prod";
}
