/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { PartialTestResultCatHSchema } from './partial';
import { TestResultCommonSchema } from '../common/index';
import { TestData as PartialCatHTestData } from './partial';
import { TestData as CommonTestData } from '../common';
import { TestRequirements as PartialCatHTestRequirements } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';
import { Manoeuvres as PartialCatHManoeuvres } from './partial';
import { VehicleChecks as PartialCatHVehicleChecks } from './partial';
import { JournalData as PartialCatHJournalData } from './partial';
import { JournalData as CommonJournalData } from '../common/index';
import { Candidate as PartialCatHCandidate } from './partial';
import { Candidate as CommonCandidate } from '../common/index';
import { VehicleDetails as PartialCatHVehicleDetails } from './partial';
import { VehicleDetails as CommonVehicleDetails } from '../common/index';
import { PassCompletion as CommonPassCompletion } from '../common/index';

export declare namespace CatHUniqueTypes {
  type TestResult = PartialTestResultCatHSchema & TestResultCommonSchema;

  type TestData = PartialCatHTestData & CommonTestData;

  type TestRequirements = PartialCatHTestRequirements & CommonTestRequirements;

  type Manoeuvres = PartialCatHManoeuvres;

  type VehicleChecks = PartialCatHVehicleChecks;

  type JournalData = PartialCatHJournalData & CommonJournalData;

  type Candidate = PartialCatHCandidate & CommonCandidate;

  type VehicleDetails = PartialCatHVehicleDetails & CommonVehicleDetails;

}
