import { Name, ActivityCode } from "../mes-test-schema/categories/B";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SearchResultTestSchema {
  /**
   * Search result schema
   */
  costCode: string;
  testDate: Date;
  staffNumber: string;
  candidateName: Name;
  applicationReference: string;
  category: string;
  activityCode: ActivityCode;
}


