/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { PartialTestResultCatKSchema } from './partial';
import { TestResultCommonSchema } from '../common/index';
import { TestData as PartialCatKTestData } from './partial';
import { TestData as CommonTestData } from '../common';
import { TestRequirements as PartialCatKTestRequirements } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';
import { VehicleChecks as PartialCatKVehicleChecks } from './partial';
import { JournalData as PartialCatKJournalData } from './partial';
import { JournalData as CommonJournalData } from '../common/index';
import { Candidate as PartialCatKCandidate } from './partial';
import { Candidate as CommonCandidate } from '../common/index';
import { ControlledStop as PartialCatKControlledStop } from './partial';
import { HighwayCodeSafety as PartialCatKHighwayCodeSafety } from './partial';

export declare namespace CatKUniqueTypes {
  type TestResult = PartialTestResultCatKSchema & TestResultCommonSchema;

  type TestData = PartialCatKTestData & CommonTestData;

  type TestRequirements = PartialCatKTestRequirements & CommonTestRequirements;

  type VehicleChecks = PartialCatKVehicleChecks;

  type JournalData = PartialCatKJournalData & CommonJournalData;

  type Candidate = PartialCatKCandidate & CommonCandidate;

  type ControlledStop = PartialCatKControlledStop;

  type HighwayCodeSafety = PartialCatKHighwayCodeSafety;
}
