/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { PartialTestResultCatFSchema } from './partial';
import { TestResultCommonSchema } from '../common/index';
import { TestData as PartialCatFTestData } from './partial';
import { TestData as CommonTestData } from '../common';
import { TestRequirements as PartialCatFTestRequirements } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';
import { Manoeuvres as PartialCatFManoeuvres } from './partial';
import { VehicleChecks as PartialCatFVehicleChecks } from './partial';
import { JournalData as PartialCatFJournalData } from './partial';
import { JournalData as CommonJournalData } from '../common/index';
import { Candidate as PartialCatFCandidate } from './partial';
import { Candidate as CommonCandidate } from '../common/index';
import { VehicleDetails as PartialCatFVehicleDetails } from './partial';
import { VehicleDetails as CommonVehicleDetails } from '../common/index';
import { PassCompletion as CommonPassCompletion } from '../common/index';

export declare namespace CatFUniqueTypes {
  type TestResult = PartialTestResultCatFSchema & TestResultCommonSchema;

  type TestData = PartialCatFTestData & CommonTestData;

  type TestRequirements = PartialCatFTestRequirements & CommonTestRequirements;

  type Manoeuvres = PartialCatFManoeuvres;

  type VehicleChecks = PartialCatFVehicleChecks;

  type JournalData = PartialCatFJournalData & CommonJournalData;

  type Candidate = PartialCatFCandidate & CommonCandidate;

  type VehicleDetails = PartialCatFVehicleDetails & CommonVehicleDetails;

}
