/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { PartialTestResultCatDSchema } from './partial';
import { TestResultCommonSchema } from '../common/index';
import { TestData as PartialCatDTestData } from './partial';
import { TestData as CommonTestData } from '../common';
import { TestRequirements as PartialCatDTestRequirements } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';
import { Manoeuvres as PartialCatDManoeuvres } from './partial';
import { VehicleChecks as PartialCatDVehicleChecks } from './partial';
import { JournalData as PartialCatDJournalData } from './partial';
import { JournalData as CommonJournalData } from '../common/index';
import { Candidate as PartialCatDCandidate } from './partial';
import { Candidate as CommonCandidate } from '../common/index';
import { VehicleDetails as PartialCatDVehicleDetails } from './partial';
import { VehicleDetails as CommonVehicleDetails } from '../common/index';
import { PcvDoorExercise as PartialPcvDoorExercise } from './partial';
import { PassCompletion as PartialPassCompletion } from './partial';
import { PassCompletion as CommonPassCompletion } from '../common/index';

export declare namespace CatDUniqueTypes {
  type TestResult = PartialTestResultCatDSchema & TestResultCommonSchema;

  type TestData = PartialCatDTestData & CommonTestData;

  type TestRequirements = PartialCatDTestRequirements & CommonTestRequirements;

  type Manoeuvres = PartialCatDManoeuvres;

  type VehicleChecks = PartialCatDVehicleChecks;

  type JournalData = PartialCatDJournalData & CommonJournalData;

  type Candidate = PartialCatDCandidate & CommonCandidate;

  type VehicleDetails = PartialCatDVehicleDetails & CommonVehicleDetails;

  type PassCompletion = PartialPassCompletion & CommonPassCompletion;

  type PcvDoorExercise = PartialPcvDoorExercise;
}
