/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The count of the number of driving faults recorded against a test element
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "drivingFaultCount".
 */
export type DrivingFaultCount = number;
/**
 * Comments recorded against a fault
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "faultComments".
 */
export type FaultComments = string;
/**
 * Indicator for a serious fault being recorded against a test element
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "seriousFaultIndicator".
 */
export type SeriousFaultIndicator = boolean;
/**
 * Indicator for a dangerous fault being recorded against a test element
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "dangerousFaultIndicator".
 */
export type DangerousFaultIndicator = boolean;
/**
 * Name of the business the candidate relates to
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "businessName".
 */
export type BusinessName = string;
/**
 * Telephone number of the business the candidate relates to
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "businessTelephone".
 */
export type BusinessTelephone = string;
/**
 * Indicates whether the bike belongs to a driving school
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "schoolBike".
 */
export type SchoolBike = boolean;
/**
 * The possible outcomes of any manoeuvre performed during the test
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "controlledStopOutcome".
 */
export type ControlledStopOutcome = "DF" | "S" | "D";
/**
 * Indicator for a controlled stop being performed during the test
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "controlledStopIndicator".
 */
export type ControlledStopIndicator = boolean;

export interface PartialTestResultCatAM1Schema {
  testData?: TestData;
  journalData: JournalData;
  vehicleDetails?: VehicleDetails;
}
/**
 * Data associated with the test
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "testData".
 */
export interface TestData {
  ETA?: ETA;
  drivingFaults?: DrivingFaults;
  seriousFaults?: SeriousFaults;
  dangerousFaults?: DangerousFaults;
  emergencyStop?: EmergencyStop;
  avoidance?: Avoidance;
}
/**
 * Indicates whether the examiner had to take physical or verbal action during the test
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "ETA".
 */
export interface ETA {
  /**
   * Indicates that the examiner had to take physical action
   */
  physical?: boolean;
  /**
   * Indicates that the examiner had to take verbal action
   */
  verbal?: boolean;
}
/**
 * The driving faults accumulated during the test
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "drivingFaults".
 */
export interface DrivingFaults {
  useOfStand?: DrivingFaultCount;
  useOfStandComments?: FaultComments;
  manualHandling?: DrivingFaultCount;
  manualHandlingComments?: FaultComments;
  slalom?: DrivingFaultCount;
  slalomComments?: FaultComments;
  slowControl?: DrivingFaultCount;
  slowControlComments?: FaultComments;
  uTurn?: DrivingFaultCount;
  uTurnComments?: FaultComments;
  controlledStop?: DrivingFaultCount;
  controlledStopComments?: FaultComments;
  precautions?: DrivingFaultCount;
  precautionsComments?: FaultComments;
  moveOffSafety?: DrivingFaultCount;
  moveOffSafetyComments?: FaultComments;
  moveOffControl?: DrivingFaultCount;
  moveOffControlComments?: FaultComments;
  avoidance?: DrivingFaultCount;
  avoidanceComments?: FaultComments;
  emergencyStop?: DrivingFaultCount;
  emergencyStopComments?: FaultComments;
}
/**
 * The serious faults accumulated during the test
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "seriousFaults".
 */
export interface SeriousFaults {
  useOfStand?: SeriousFaultIndicator;
  useOfStandComments?: FaultComments;
  manualHandling?: SeriousFaultIndicator;
  manualHandlingComments?: FaultComments;
  slalom?: SeriousFaultIndicator;
  slalomComments?: FaultComments;
  slowControl?: SeriousFaultIndicator;
  slowControlComments?: FaultComments;
  uTurn?: SeriousFaultIndicator;
  uTurnComments?: FaultComments;
  controlledStop?: SeriousFaultIndicator;
  controlledStopComments?: FaultComments;
  precautions?: SeriousFaultIndicator;
  precautionsComments?: FaultComments;
  moveOffSafety?: SeriousFaultIndicator;
  moveOffSafetyComments?: FaultComments;
  moveOffControl?: SeriousFaultIndicator;
  moveOffControlComments?: FaultComments;
  avoidance?: SeriousFaultIndicator;
  avoidanceComments?: FaultComments;
  emergencyStop?: SeriousFaultIndicator;
  emergencyStopComments?: FaultComments;
}
/**
 * The dangerous faults accumulated during the test
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "dangerousFaults".
 */
export interface DangerousFaults {
  useOfStand?: DangerousFaultIndicator;
  useOfStandComments?: FaultComments;
  manualHandling?: DangerousFaultIndicator;
  manualHandlingComments?: FaultComments;
  slalom?: DangerousFaultIndicator;
  slalomComments?: FaultComments;
  slowControl?: DangerousFaultIndicator;
  slowControlComments?: FaultComments;
  uTurn?: DangerousFaultIndicator;
  uTurnComments?: FaultComments;
  controlledStop?: DangerousFaultIndicator;
  controlledStopComments?: FaultComments;
  precautions?: DangerousFaultIndicator;
  precautionsComments?: FaultComments;
  moveOffSafety?: DangerousFaultIndicator;
  moveOffSafetyComments?: FaultComments;
  moveOffControl?: DangerousFaultIndicator;
  moveOffControlComments?: FaultComments;
  avoidance?: DangerousFaultIndicator;
  avoidanceComments?: FaultComments;
  emergencyStop?: DangerousFaultIndicator;
  emergencyStopComments?: FaultComments;
}
/**
 * The outcome of emergency stop tests
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "emergencyStop".
 */
export interface EmergencyStop {
  /**
   * The speed of the first attempt
   */
  firstAttempt?: number;
  /**
   * The speed of the second attempt
   */
  secondAttempt?: number;
  /**
   * Whether the required speed was not met
   */
  speedNotMet?: boolean;
  [k: string]: any;
}
/**
 * The outcome of avoidance tests
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "avoidance".
 */
export interface Avoidance {
  /**
   * The speed of the first attempt
   */
  firstAttempt?: number;
  /**
   * The speed of the second attempt
   */
  secondAttempt?: number;
  /**
   * Whether the required speed was not met
   */
  speedNotMet?: boolean;
  [k: string]: any;
}
/**
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "journalData".
 */
export interface JournalData {
  candidate: Candidate;
}
/**
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "candidate".
 */
export interface Candidate {
  businessAddress?: Address;
  businessName?: BusinessName;
  businessTelephone?: BusinessTelephone;
}
/**
 * Details of the address
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "address".
 */
export interface Address {
  /**
   * First line of address
   */
  addressLine1?: string;
  /**
   * Second line of address
   */
  addressLine2?: string;
  /**
   * Third line of address
   */
  addressLine3?: string;
  /**
   * Fourth line of address
   */
  addressLine4?: string;
  /**
   * Fifth line of address
   */
  addressLine5?: string;
  /**
   * The address postcode
   */
  postcode?: string;
}
/**
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "vehicleDetails".
 */
export interface VehicleDetails {
  schoolBike?: SchoolBike;
}
/**
 * Data needs capturing for a manoeuvre competency
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "manoeuvre".
 */
export interface Manoeuvre {
  controlFault?: ControlledStopOutcome;
  controlFaultComments?: FaultComments;
  observationFault?: ControlledStopOutcome;
  observationFaultComments?: FaultComments;
  /**
   * Indicator for a manoeuvre being performed during the test
   */
  selected?: boolean;
}
/**
 * Result of a vehicle checks question
 *
 * This interface was referenced by `PartialTestResultCatAM1Schema`'s JSON-Schema
 * via the `definition` "questionResult".
 */
export interface QuestionResult {
  /**
   * Code representing the question that was asked
   */
  code?: string;
  /**
   * Description of the question that was asked
   */
  description?: string;
  /**
   * Outcome of the question that was asked
   */
  outcome?: "P" | "DF" | "S" | "D";
}
