/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { PartialTestResultADI2Schema } from './partial';
import { TestResultCommonSchema } from '../common';
import { TestData as PartialADI2TestData } from './partial';
import { TestData as CommonTestData } from '../common/index';
import { ControlledStop as PartialADI2ControlledStop } from './partial';
import { Manoeuvres as PartialADI2Manoeuvres } from './partial';
import { TrainerDetails as PartialADI2TrainerDetails } from './partial';
import { TestRequirements as PartialADI2TestRequirements } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';
import { VehicleChecks as PartialADI2VehicleChecks } from './partial';
import { VehicleDetails as PartialADI2VehicleDetails } from './partial';
import { VehicleDetails as CommonVehicleDetails } from '../common/index';

export declare namespace CatADI2UniqueTypes {
  type TestResult = PartialTestResultADI2Schema & TestResultCommonSchema;

  type TestData = PartialADI2TestData & CommonTestData;

  type ControlledStop = PartialADI2ControlledStop;

  type TestRequirements = PartialADI2TestRequirements & CommonTestRequirements;

  type VehicleChecks = PartialADI2VehicleChecks;

  type Manoeuvres = PartialADI2Manoeuvres;

  type VehicleDetails = PartialADI2VehicleDetails & CommonVehicleDetails;

  type TrainerDetails = PartialADI2TrainerDetails;
}
