/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The possible outcomes of any manoeuvre performed during the test
 *
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "manoeuvreOutcome".
 */
export type ManoeuvreOutcome = "DF" | "S" | "D";

export interface PartialTestResultADI2Schema {
  testData?: TestData;
  vehicleDetails?: VehicleDetails;
  preTestDeclarations?: PreTestDeclarations;
}
/**
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "testData".
 */
export interface TestData {
  eyesightTest?: EyesightTest;
  testRequirements?: TestRequirements;
  manoeuvre1?: Manoeuvre1;
  manoeuvre2?: Manoeuvre2;
  vehicleChecks?: VehicleChecks;
  controlledStop?: ControlledStop;
}
/**
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "eyesightTest".
 */
export interface EyesightTest {
  complete?: boolean;
  /**
   * Whether the candidate has failed the eyesight test
   */
  seriousFault?: boolean;
  /**
   * Comments recorded against a fault
   */
  faultComments?: string;
}
/**
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "testRequirements".
 */
export interface TestRequirements {
  /**
   * Indicates whether or not this test requirement was carried out
   */
  uphillStart?: boolean;
  /**
   * Indicates whether or not this test requirement was carried out
   */
  downhillStart?: boolean;
  /**
   * Indicates whether or not this test requirement was carried out
   */
  angledStart?: boolean;
}
/**
 * The first manoeuvre that was carried out during the test and any faults recorded against it
 *
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "manoeuvre1".
 */
export interface Manoeuvre1 {
  forwardPark?: Manoeuvre;
  reverseParkCarpark?: Manoeuvre;
  reverseParkRoad?: Manoeuvre;
  reverseRight?: Manoeuvre;
}
/**
 * Data needs capturing for a manoeuvre competency
 *
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "manoeuvre".
 */
export interface Manoeuvre {
  controlFault?: ManoeuvreOutcome;
  /**
   * Comments recorded against a fault
   */
  controlFaultComments?: string;
  observationFault?: ManoeuvreOutcome;
  /**
   * Comments recorded against a fault
   */
  observationFaultComments?: string;
  /**
   * Indicator for a manoeuvre being performed during the test
   */
  selected?: boolean;
}
/**
 * The second manoeuvre that was carried out during the test and any faults recorded against it
 *
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "manoeuvre2".
 */
export interface Manoeuvre2 {
  forwardPark?: Manoeuvre;
  reverseParkCarpark?: Manoeuvre;
  reverseParkRoad?: Manoeuvre;
  reverseRight?: Manoeuvre;
}
/**
 * Details of the Tell Me questions asked during the test
 *
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "vehicleChecks".
 */
export interface VehicleChecks {
  tellMeQuestions?: QuestionResult[];
  /**
   * Comments recorded against a fault
   */
  tellMeComments?: string;
}
/**
 * Result of a vehicle checks question
 *
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "questionResult".
 */
export interface QuestionResult {
  /**
   * Code representing the question that was asked
   */
  code?: string;
  /**
   * Description of the question that was asked
   */
  description?: string;
  /**
   * Outcome of the question that was asked
   */
  outcome?: "P" | "DF" | "S" | "D";
}
/**
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "controlledStop".
 */
export interface ControlledStop {
  fault?: ManoeuvreOutcome;
  /**
   * Comments recorded against a fault
   */
  faultComments?: string;
  /**
   * Indicator for a manoeuvre being performed during the test
   */
  selected?: boolean;
}
/**
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "vehicleDetails".
 */
export interface VehicleDetails {
  /**
   * Indicates whether the vehicle belongs to a driving school
   */
  schoolCar?: boolean;
  /**
   * Indicates whether or not the vehicle has dual controls fitted
   */
  dualControls?: boolean;
}
/**
 * This interface was referenced by `PartialTestResultADI2Schema`'s JSON-Schema
 * via the `definition` "preTestDeclarations".
 */
export interface PreTestDeclarations {
  /**
   * Whether or not the candidate has declared that their test vehicle has a valid insurance policy
   */
  insuranceDeclarationAccepted: boolean;
  /**
   * Base 64 encoded binary data representing a PNG image of the candidates signature
   */
  preTestSignature: string;
}
