/* tslint:disable */
/**
 * This file was initially generated by json-schema-to-typescript.
 * IT HAS SINCE BEEN MOFIIED BY HAND. DO NOT REGENERATE
 */

// Always follow the order of the properties that are in partial.d.ts
import { PartialTestResultCatD1Schema } from './partial';
import { TestResultCommonSchema } from '../common/index';
import { TestData as PartialCatD1TestData } from './partial';
import { TestData as CommonTestData } from '../common';
import { TestRequirements as PartialCatD1TestRequirements } from './partial';
import { TestRequirements as CommonTestRequirements } from '../common/index';
import { Manoeuvres as PartialCatD1Manoeuvres } from './partial';
import { VehicleChecks as PartialCatD1VehicleChecks } from './partial';
import { JournalData as PartialCatD1JournalData } from './partial';
import { JournalData as CommonJournalData } from '../common/index';
import { Candidate as PartialCatD1Candidate } from './partial';
import { Candidate as CommonCandidate } from '../common/index';
import { VehicleDetails as PartialCatD1VehicleDetails } from './partial';
import { VehicleDetails as CommonVehicleDetails } from '../common/index';
import { SafetyQuestionResult as PartialSafetyQuestionResult } from './partial';
import { PcvDoorExercise as PartialPcvDoorExercise } from './partial';

export declare namespace CatD1UniqueTypes {
  type TestResult = PartialTestResultCatD1Schema & TestResultCommonSchema;

  type TestData = PartialCatD1TestData & CommonTestData;

  type TestRequirements = PartialCatD1TestRequirements & CommonTestRequirements;

  type Manoeuvres = PartialCatD1Manoeuvres;

  type VehicleChecks = PartialCatD1VehicleChecks;

  type JournalData = PartialCatD1JournalData & CommonJournalData;

  type Candidate = PartialCatD1Candidate & CommonCandidate;

  type VehicleDetails = PartialCatD1VehicleDetails & CommonVehicleDetails;

  type SafetyQuestion = PartialSafetyQuestionResult;

  type PcvDoorExercise = PartialPcvDoorExercise;
}
