name: Publish package

on:
  workflow_dispatch:
    inputs:
      directory:
        description: Directory of schema
        required: true
        type: choice
        options:
          - mes-config-schema
          - mes-driver-schema
          - mes-journal-schema
          - mes-search-schema
          - mes-test-schema

jobs:
  publish:
    uses: dvsa/des-workflow-actions/.github/workflows/publish-package.yaml@main
    with:
      WORKING_DIRECTORY: ${{ inputs.directory }}
      PACKAGE_NAME: ${{ format('{0}/{1}', '@dvsa', inputs.directory) }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.DES_ACCESS_TOKEN }}
